### ISSUE TITLE
Windows/IIS: Doesn't work with Symfony's Process but with exec()

### ISSUE THREAD

**Issue by IwfY** [KnpLabs/snappy#308] opened 2018-04-09 17:10 UTC
I'm trying to use Snappy on Windows Server 2012 R2 with IIS (PHP 7.2) x64. I installed WkHtmlToPdf 0.12.4 x64 to a spaceless directory and gave IUSR and IIS_IUSRS execute permission on the executable.

It's in an Symfony 3.4 application with the Snappy-Bundle.

When triggered I get this error message:

    request.CRITICAL: Uncaught PHP Exception RuntimeException: "The file 'C:\inetpub\wwwroot\AppXYZ\var\cache\dev/snappy\knp_snappy5acb743f2f3ed4.87121945.pdf' was not created

Command:

    "C:\inetpub\wwwroot\AppXYZ\app/../bin/wkhtmltopdf.exe" --lowquality --margin-bottom "25" --margin-top "35" --page-size "A4" --quiet --encoding "utf-8" --disable-javascript --zoom "0.8" --footer-html "C:\inetpub\wwwroot\AppXYZ\var\cache\dev/snappy\knp_snappy5acb9a69ba2c22.13116553.html" --footer-spacing "10" --header-html "C:\inetpub\wwwroot\AppXYZ\var\cache\dev/snappy\knp_snappy5acb9a69ba4ba2.68180388.html" --header-spacing "10" "C:\inetpub\wwwroot\AppXYZ\var\cache\dev/snappy\knp_snappy5acb9a69b9fea9.46414520.html" "C:\inetpub\wwwroot\AppXYZ\var\cache\dev/snappy\knp_snappy5acb9a69ba1cd3.87916872.pdf"

The command runs flawless from a CMD.

Also if I replace the usage of *\Symfony\Component\Process\Process* in *\Knp\Snappy\AbstractGenerator->executeCommand* with a call using *exec()* it works fine and produces the PDF file.

    protected function executeCommand($command)
    {
        $out = null;
        $ret = null;
        exec($command, $out, $ret);
        
        return [
            $ret,
            $out,
            '',
        ];
    }

Can someone point me to a possible reason for this behaviour?

**Comment by IwfY** [comment] 2018-04-10 09:30
It works too if I disable the Process output in *\Knp\Snappy\AbstractGenerator->executeCommand*:

    /**
     * Executes the given command via shell and returns the complete output as
     * a string.
     *
     * @param string $command
     *
     * @return array(status, stdout, stderr)
     */
    protected function executeCommand($command)
    {        
        $process = new Process($command, null, $this->env);

        // this:
        $process->disableOutput();


        if (false !== $this->timeout) {
            $process->setTimeout(50);
        }

        $process->run();

        return [
            $process->getExitCode(),
            '',// $process->getOutput(),
            ''//$process->getErrorOutput(),
        ];
    }

**Comment by plasticneko** [comment] 2018-05-02 06:13
I wanted to add to this in the event another person is struggling with Snappy not working:

Snappy only works for me if I use **Symfony/Process** version **3.4.6**, when on Linux (CentOS). All other versions tend to produce a handful of errors I can't track. As for Mac (High Sierra), everything is working as intended. 

I can't confirm whether there are any versioning issues with Windows at the moment, however.

**Comment by alexpozzi** [comment] 2019-10-11 14:26
I'm going to close the issue (as it's dating 2018).
Please reopen the issue if it's still relevant.
If, in the meantime, you found the solution please share it :)

**Closed by alexpozzi** 2019-10-11 14:26 UTC
