### ISSUE TITLE
Doesn't accept Chinese characters

### ISSUE THREAD

**Issue by leeuwk004** [KnpLabs/snappy#239] opened 2017-03-17 14:49 UTC
I use the bundle to create sales overviews, and some of the products that are being sold can be sold either to or from china. However I think the bundle doesn't really like Chinese characters. Is this something that can be fixed?

![image](https://cloud.githubusercontent.com/assets/17140548/24048484/58374d9c-0b29-11e7-9916-8b1f1351dfe6.png)

**Comment by sstok** [comment] 2017-06-17 08:28
Make sure the proper encoding is set in the HTML, as snappy is nothing more then a wrapper around wkhtml can check if opening the generated HTML display's correctly in the browser.

**Comment by sstok** [comment] 2017-06-17 08:33
Maybe related to #194

**Comment by daudmalik06** [comment] 2017-07-14 23:40
@leeuwk004 @jakenoble there are some limitations with wkhtmltopdf for this purpose born new library which uses chrome headless as a back-end so no more these kind of problems try this 
https://github.com/daudmalik06/PhpChromeToPdf

**Comment by NiR-** [comment] 2017-07-25 09:02
@daudmalik06 Thanks to not pollute every issue with your ads... Note that "limitations of wkhtmltopdf" you're talking about are, most of the time, not limitations but rather misconfigured servers. Because wkhtmltopdf's deps are hard to configure, servers running it should be configured by real sysadmins, not devs...

@leeuwk004 I confirm I was able to create a pdf of https://wuu.wikipedia.org/wiki/PHP. Neither wkhtmltopdf nor snappy have any problem with locales. As stated by sstok you should double check your html, it looks like an encoding issue in your html file. I retag this as "need help". Since the answer has already been provided one month ago, I will close this next week with no answer on your behalf.

**Comment by daudmalik06** [comment] 2017-07-25 09:17
@NiR-  i didn't meant to spam , in fact i had 
several issues(difficult configuration, xvfb daemon etc etc..) too with this class,  
and i was really annoyed by these difficulties cause once i was fan of wkhtmltopdf  
if you felt i did spam , then i ask sorry :)
Best Regards

**Comment by NiR-** [comment] 2017-09-12 19:45
@leeuwk004 Could you provide a reasonable php+html reproducer so I could test it on my side, please? Would be simpler for us to help you based on facts rather than assumptions.

**Closed** 2019-09-27 14:32 UTC
Labels: Need help, Waiting for OP's input, locale
