### ISSUE TITLE
use of Process fails render

### ISSUE THREAD

**Issue by dlevacher** [KnpLabs/snappy#134] opened 2015-01-12 14:57 UTC
I am using [KnpSnappyBundle](https://github.com/KnpLabs/KnpSnappyBundle) to generate a pdf from a view, but I get a `Exit with code 1 due to network error: HostNotFoundError` when using (default) `\Symfony\Component\Process\Process` in the `protected function executeCommand($command)` of [`AbstractGenerator`](https://github.com/KnpLabs/snappy/blob/master/src/Knp/Snappy/AbstractGenerator.php) class.
If I bypass the test and use the Snappy [`Process`](https://github.com/KnpLabs/snappy/blob/master/src/Knp/Snappy/Process.php) class I get a render, but with no css or images.
If I use the command line directly, the generated pdf is good. It is the same if instead of [`Process`](https://github.com/KnpLabs/snappy/blob/master/src/Knp/Snappy/Process.php) class I call directly `exec($command)`
Any idea why would that be ?

For now I use `exec($command, $output, $return); return array($return, $output, null);` in executeCommand from [`AbstractGenerator`](https://github.com/KnpLabs/snappy/blob/master/src/Knp/Snappy/AbstractGenerator.php) as it is working for me.

I am using the latests versions : 
* wkhtmltopdf 0.12.2
* Snappy [0.3.2](https://github.com/KnpLabs/snappy/tree/0.3.2)
* SnappyBundle [1.2](https://github.com/KnpLabs/KnpSnappyBundle/tree/v1.2)

**Comment by mgrajcarek** [comment] 2015-01-21 12:45
Sam issue for me on Windows platform.

**Comment by Misiur** [comment] 2015-02-05 16:35
+1 encountered something similar today. If the html doesn't contain any external resources pdf is generated. Running wkhtmltopdf from command line manually works as correctly. 
When running with symfony process-like command 
```cmd /V:ON /E:ON /C "("D:\Programy\wkhtmlpdf\bin\wkhtmltopdf.exe" --lowquality test.html test.pdf) 1>"1file.tmp" 2>"2file.tmp""``` the pdf is not generated, but this is not a completely valid test as I'm not using proc_open. googling HostNotFoundError didn't get me far as well.

**Comment by TheBeakerMan** [comment] 2015-02-23 19:52
We are getting the same problem here as well (since the 0.3.2 update) did any of you find a resolution to this problem?  Executing the command line works fine, but we get the HostNotFoundError error from the bundle.

**Comment by gnutix** [comment] 2015-03-01 18:54
Same here using SnappyBundle and generating the PDF from a SF2 action.

**Comment by docteurklein** [comment] 2015-03-05 11:47
what is the exit status code of the command in a terminal?

**Comment by dlevacher** [comment] 2015-03-05 13:01
The exit status code is 0 if I run the command : 
`C:\PROGRA~1\wkhtmltopdf\bin\wkhtmltopdf.exe --lowquality --margin-bottom "8" --margin-left "8" --margin-right "8" --margin-top "8" --page-size "A4" --title "20140630-140030" "C:\WINDOWS\TEMP\knp_snappy54f8531bd2e882.33083453.html" "C:\WINDOWS\TEMP\knp_snappy54f8531bd45497.00254351.pdf"`

**Comment by TheBeakerMan** [comment] 2015-03-05 13:06
For us, i've discovered what the problem is here.  The recent change added the $env parameter to the pdf.php file, which is using the PHP HINT for 'array' datatype, so if you were to pass NULL to that (the default) PHP still sees that then as an empty Array.  The problem comes later when the Process method is called and it passes the variable #this->env (which is now no longer null but an empty array).  The problem then happens in the following code in the process class

        if (null !== $env) {
            $this->setEnv($env);
        }

before that change this code never ran, it would never set the env of the process class because $env USED to be null, but now it is not, so seems like setting an empty array in the process class is causing the problem.

I think what should happen is the code in the snappy bundle that added that new parameter puts a check that if the $env is an empty array to pass NULL to the Process method (or some change along those lines).

we had to revert back to the previous version for now and i've not had a chance to submit this yet.

Hope this helps point anyone in the right direction.

**Comment by dlevacher** [comment] 2015-03-05 13:16
@TheBeakerMan is right, if `$this->env` is forced to `null` I don't get any error.

**Comment by akovalyov** [comment] 2015-08-07 10:33
Closed by https://github.com/KnpLabs/snappy/pull/143

**Closed by akovalyov** 2015-08-07 10:33 UTC
